### ISSUE TITLE
How to use reverse query in Reactjs

### ISSUE THREAD

**Issue by ahmadkam72** [cedarstudios/cedarmaps-web-sdk-raster#1]
I want to use reverse query in my reactjs project but I dont know how to import "L" component in my project.
what is L in below line and how can I import it to my reactjs project?
` var geocoder = L.cedarmaps.geocoder('cedarmaps.streets');`

Thank you.

**Comment by mohsentaleb** [comment]
In `cedarmaps-web-sdk-raster` libarary, `L` is an object, which is created in global scope by importing CedarMaps in your page. For using API in React, please checkout https://www.npmjs.com/package/@cedarstudios/cedarmaps-geo-tools

**Comment by ahmadkam72** [comment]
Have you a complete example for using cedarmaps components and features in Reactjs ?
I found examples related to js and can not use them in my Reactjs project.

**Comment by mohsentaleb** [comment]
This issue is irrelevant to this repository.

**Comment by ahmadkam72** [comment]
سلام
میشه از کامپوننت هایی که برای React native قرار دادین تو پروژه های ReactJS
استفاده کرد؟
با تشکر

**Comment by nimolix** [comment]
Please ask your question in related repo. This issue is already closed!
