### ISSUE TITLE
how to select 1 location using cedarmaps ?

### ISSUE THREAD

**Issue by mohsenfathi** [cedarstudios/cedarmaps-web-sdk-raster#2]
Hello
I want find and select location using Cedarmaps map like this link :
https://devs.cedarmaps.com/widgets.html#/ContactMap
how i can do it ?

**Comment by mohsentaleb** [comment]
CedarMaps uses the popular [Leaflet](https://leafletjs.com) library for map view / markers functionality. So you may read its documentations (section [Popup](https://leafletjs.com/reference-1.5.0.html#popup)) regarding your issue. It's as easy as writing: 
```js
marker.bindPopup('Hello World!')
```
